# Generated by Django 5.0.6 on 2024-07-21 08:51

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('media', models.FileField(upload_to=core.models.dynamic_media_path)),
                ('sent_timestamp', models.DateTimeField(auto_now_add=True)),
                ('deliverd_timestamp', models.DateTimeField(blank=True, null=True)),
                ('seen_timestamp', models.DateTimeField(blank=True, null=True)),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chathistory')),
                ('reply_of', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='replies', to='core.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
