# Generated by Django 5.0.6 on 2024-08-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='deliverd_timestamp',
            new_name='delivered_timestamp',
        ),
    ]
