# Generated by Django 5.0.6 on 2024-08-03 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date',
            new_name='date_of_birth',
        ),
    ]
