# Generated by Django 5.0.6 on 2024-08-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_userprofile_user_alter_userstatus_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstatus',
            name='last_seen',
            field=models.DateTimeField(null=True),
        ),
    ]
